service: pcpApi-docs
frameworkVersion: '4.x.x'

provider:
  name: aws
  runtime: nodejs22.x
  versionFunctions: false
  stage: ${opt:stage, "dev"}
  region: "ap-south-1"
  endpointType: ${file(${self:custom.envFilePath}):apiGatewayEndpointType}
  deploymentBucket:
    name: pcp-api-deployments-${self:provider.stage}
  environment:
    ${file(../../shared/commonEnvVars.yml):commonEnvVars}
  vpc:
    securityGroupIds: ${file(${self:custom.envFilePath}):vpc.lambdaSecurityGroupIds}
    subnetIds: ${file(${self:custom.envFilePath}):vpc.subnetIds}
  iam:
    role:
      statements:
        - ${file(../../shared/commonIAMRoleStatements.yml):firehosePutRecord}
custom:
  envFilePath: '../../environment/env.json'
  customDomain:
    basePath: docs
    domainName: ${file(${self:custom.envFilePath}):apiDomain}
    certificateName: ${file(${self:custom.envFilePath}):sslCertificateName}
    stage: ${self:provider.stage}
  serverless-offline:
    httpPort: 3005
    lambdaPort: 4005
    noPrependStageInUrl: true
    noTimeout: true
    verbose: true
    prefix: 'docs'

package:
  exclude:
    - ./**
  include:
    - ./.dist/**

plugins:
  - serverless-offline
  - serverless-domain-manager

functions:
  docsApi:
    handler: .dist/main.handler
    environment:
      userPoolDomain: ${cf:slsApi-infrastructure-${self:provider.stage}.SLSApiCognitoDomain${self:provider.stage}}
      userPoolClientId: ${cf:slsApi-infrastructure-${self:provider.stage}.SLSApiClientId${self:provider.stage}}
      slsApiDomain: ${file(${self:custom.envFilePath}):apiDomain}
    events:
      - http:
          method: GET
          cors:
            origin: '*'
            headers: ${file(../../shared/slsConfig.yml):allowedCorsHeaders}
          path: /
      - http:
          method: GET
          cors:
            origin: '*'
            headers: ${file(../../shared/slsConfig.yml):allowedCorsHeaders}
          path: /swagger.json


