service: pcpApi-user
frameworkVersion: '4.x.x'

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1800
  versionFunctions: false
  stage: ${opt:stage, "dev"}
  region: 'ap-southeast-1'
  endpointType: ${file(${self:custom.envFilePath}):apiGatewayEndpointType}
  deploymentBucket:
    name: ${self:provider.environment.DEPLOYMENT_BUCKET_NAME}
  environment: ${file(../../shared/commonEnvVars.yml):commonEnvVars}
  # vpc:
  #   securityGroupIds: ${file(${self:custom.envFilePath}):vpc.lambdaSecurityGroupIds}
  #   subnetIds: ${file(${self:custom.envFilePath}):vpc.subnetIds}
  iam:
    role:
      statements:
        - ${file(../../shared/commonIAMRoleStatements.yml):firehosePutRecord}
        - ${file(../../shared/commonIAMRoleStatements.yml):rdsAccess}
        - ${file(../../shared/commonIAMRoleStatements.yml):secretsManager}

custom:
  envFilePath: '../../environment/env.json'
  customDomain:
    basePath: user
    domainName: ${file(${self:custom.envFilePath}):apiDomain}
    certificateName: ${file(${self:custom.envFilePath}):sslCertificateName}
    stage: ${self:provider.stage}
  serverless-offline:
    httpPort: 3001
    lambdaPort: 4001
    noPrependStageInUrl: true
    noTimeout: true
    verbose: true
    prefix: ''
  cognitoUserPoolArn: ${cf:pcp-${self:provider.stage}-infrastructure-stack.PCPApiUserPoolArn${self:provider.stage}}

package:
  exclude:
    - ./**
  include:
    - ./.dist/**

plugins:
  - serverless-offline
  - serverless-domain-manager

functions:
  userApi:
    handler: .dist/main.handler
    events:
      - http:
          method: GET
          cors:
            origin: '*'
            headers: ${file(../../shared/slsConfig.yml):allowedCorsHeaders}
          path: /
          authorizer:
            arn: ${self:custom.cognitoUserPoolArn}
      - http:
          method: GET
          cors:
            origin: '*'
            headers: ${file(../../shared/slsConfig.yml):allowedCorsHeaders}
          path: /docs/swagger.json
