services:
  # Core API Services for Girl Scouts POC
  user:
    path: apps/user
  
  # Girl Scouts OCR Services
  document-upload:
    path: apps/document-upload
    dependsOn: user
  ocr-processor:
    path: apps/ocr-processor
    dependsOn: document-upload
